# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  pull_request:
    types: [labeled, unlabeled, edited, synchronize]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Install GitHub Python module
        id: gh-py-mod
        run: python3 -m pip install -U github
      - name: Check Release Notes
        id: release-notes
        run: ./check_release_notes.py
