name: Status-er
on:
  pull_request:
    types: [labeled, unlabeled, edited, synchronize]

jobs:
  statusit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Set PR Status to pending
        uses: teamniteo/pull_request_status_action@v1.0.0
        with:
            # Pull Request number (Mandatory)
            pr_number: 3

            # State to apply (Mandatory)
            # Any of the (error | failure | pending | success) states
            state: pending

            # Name of the repository in {organization}/{repo_name} format (Mandatory)
            repository: danudey/pystrptime

            # Name to identify the Status (Optional)
            # Defaults to `default`
            context: default

            # The target URL to associate with the Status (Optional)
            # This URL will be linked from the Github UI to allow users to easily see the source of the status.
            target_url: https://example.target_url.com

            # A short description of the status (Optional)
            description: "An example description"

        env:
            # Default Github Token
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}